### PR TITLE
Lab 4

### PR DESCRIPTION
**Pull request by salsaman921**
hey andy..need this to pull it..thank u

### CODE REVIEW

**Comment by ac-andyta** [comment]
Hi Almaz, not sure what you're trying to do in my repository. This would override the changes in my lab 3 branch. Are you trying to get the changes for lab 4? You can clone this repository locally and checkout the lab-4 branch

**Comment by salsaman921** [comment]
sorry new to whole github...buddy told me should lont time ago created one.. and make it public for future like resume on what you worked as.... so getting sused to what and what... trying to get lab4 and to add from there for lab5....
________________________________

**Comment by salsaman921** [comment]
hi Andy I give up.... I tried in an extremely short time to code it... at this point id be coping from YouTube videos to what I understand... in an extremely short time... I'll start on lab 6 instead hoping you would give me an extension with no penalties.... believe I tried if u want id share my lab5..
________________________________

**Comment by ac-andyta** [comment]
Hi Almaz, can you email me?

**Comment by salsaman921** [comment]
email u the file?
________________________________

**Pull request closed without merging**
